app/routes.py
from quart import Blueprint, render_template, request, redirect, url_for, flash, current_app, session
from app.db import *
import bcrypt
import logging
from quart import g
from app.utils import *
logger = logging.getLogger(__name__)
main = Blueprint("main", __name__)

######################################################################
                            #Test_routes
######################################################################


@main.route("/long")
async def long_task():
    import asyncio
    await asyncio.sleep(10)  # Симулируем долгую задачу
    return "Long task done!"

@main.route("/quick")
async def quick_task():
    return "Quick task done!"

######################################################################
                    #Check_roles_before_any_request
######################################################################


@main.before_app_request
async def load_user_roles():
    user_id = session.get('user_id')
    if user_id:
        g.user_roles = await get_user_roles(current_app.db_pool, user_id)
    else:
        g.user_roles = []

######################################################################
                            #MAIN_route
######################################################################

@main.route("/", methods=["GET"])
async def home():
    """
    Главная страница сайта с возможностью поиска и фильтрации самокатов.
    """ 
    
    try:
        query = request.args.get('q', '').strip()
        location_id = request.args.get('location', '')
        status = request.args.get('status', '').strip()
        min_battery = int(request.args.get('min_battery', 0))

        user_id = session.get('user_id')  # Получаем ID текущего пользователя
        locations = await get_all_locations(current_app.db_pool)
        #logger.info(f"Current user_id from session: {user_id} (type: {type(user_id)})")
        scooters, user_has_active_reservation = await search_scooters(
            current_app.db_pool,
            query=query,
            location_id=location_id,
            status=status,
            min_battery=min_battery,
            user_id=user_id
        )
        #logger.info(f"Query: {query}, Location ID: {location_id}, Status: {status}, Min Battery: {min_battery}")
        #logger.info(f"Scooters returned: {scooters}")
        search_message = "Результаты поиска" if query or location_id or status or min_battery > 0 else None
        return await render_template(
            "home.html",
            scooters=scooters,
            locations=locations,
            search_message=search_message,
            selected_location_id=location_id,
            user_has_active_reservation=user_has_active_reservation
        )
    except Exception as e:
        logger.error(f"Ошибка при загрузке главной страницы: {e}")
        return f"Ошибка при загрузке главной страницы: {e}", 500


######################################################################
                            #User_routes
######################################################################


@main.route("/profile")
async def profile():
    """
    Страница профиля пользователя с поддержкой пагинации.
    """
    user_id = session.get("user_id")
    if not user_id:
        await flash("Пожалуйста, войдите в систему.", "warning")
        return redirect(url_for("main.login"))

    try:
        # Получаем информацию о пользователе
        user = await get_user_by_id(current_app.db_pool, user_id)
        if not user:
            await flash("Информация о пользователе не найдена.", "danger")
            return redirect(url_for("main.login"))

        # Параметры пагинации
        page = int(request.args.get("page", 1))
        limit = 5
        offset = (page - 1) * limit

        # Получаем поездки с учетом пагинации
        last_rentals = await get_last_rentals(current_app.db_pool, user_id, limit=limit, offset=offset)

        # Проверяем, есть ли следующая страница
        has_more = len(last_rentals) == limit
        has_previous = page > 1


        return await render_template(
            "profile.html",
            username=user["username"],
            email=user["email"],
            last_rentals=last_rentals,
            page=page,
            has_more=has_more,
            has_previous=has_previous
        )
    except Exception as e:
        current_app.logger.error(f"Ошибка при загрузке профиля пользователя {user_id}: {e}")
        await flash("Произошла ошибка при загрузке профиля.", "danger")
        return redirect(url_for("main.home"))



@main.route("/register", methods=["GET", "POST"])
async def register():
    """
    Регистрация нового пользователя.
    
    1. Форма запрашивает пользователя ввести username, email, password.
    1.1. Если заполнены не все поля - сброс страницы, warning.
    2. Создаётся хэш пароля для хранения в БД.
    3. Вызываем get_user_by_email для проверки уникальности пользователя, иначе - сброс страницы, warning.
    4. Вызываем create_user.
    5. Если успешно, переброс на страницу login, иначе - сброс страницы, warning.
    """

    if request.method == "POST":
        logger.info("Начат процесс регистрации.")
        form = await request.form
        username = form.get("username")
        email = form.get("email")
        password = form.get("password")

        if not username or not email or not password:
            logger.warning("Не все поля формы регистрации заполнены.")
            await flash("Все поля обязательны для заполнения!", "warning")
            return redirect(url_for("main.register"))

        hashed_password = bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")

        async with current_app.db_pool.acquire():
            try:
                # Проверяем, существует ли пользователь с таким email
                existing_user = await get_user_by_email(current_app.db_pool, email)
                if existing_user:
                    logger.warning(f"Пользователь с email {email} уже существует.")
                    await flash("Пользователь с таким email уже существует.", "danger")
                    return redirect(url_for("main.register"))

                # Создаём пользователя
                user_id = await create_user(current_app.db_pool, username, hashed_password, email)
                logger.info(f"Пользователь {email} успешно зарегистрирован с ID: {user_id}.")

                await flash("Регистрация прошла успешно! Теперь вы можете войти.", "success")
                return redirect(url_for("main.login"))
            except Exception as e:
                logger.error(f"Ошибка при регистрации пользователя {email}: {e}")
                await flash("Произошла ошибка. Попробуйте ещё раз.", "danger")
                return redirect(url_for("main.register"))

    return await render_template("register.html")

@main.route("/login", methods=["GET", "POST"])
async def login():
    """
    Авторизация пользователя.
    
    1. Форма запрашивает пользователя ввести email, password.
    1.1. Если заполнены не все поля - сброс страницы, warning.
    2. Вызываем get_user_by_email для проверки существования пользователя, 
        иначе - сброс страницы, warning.
    3. Вызываем проверку соответствия пароля: bcrypt.checkpw(введенный пароль, хранящийся пароль), 
        иначе - сброс страницы, 2 вида warning (ошибка и ValueError).
    4. Использование session для сохранения user_id, переброс на страницу home.
    """

    if request.method == "POST":
        logger.info("Начат процесс авторизации.")
        form = await request.form
        email = form.get("email")
        password = form.get("password")

        if not email or not password:
            logger.warning("Не все поля формы авторизации заполнены.")
            await flash("Все поля обязательны для заполнения!", "warning")
            return redirect(url_for("main.login"))

        try:
            # Получаем пользователя из базы данных
            user = await get_user_by_email(current_app.db_pool, email)
            if not user:
                logger.warning(f"Не найден пользователь с email {email}.")
                await flash("Неверный email или пароль. Если проблема сохраняется, обратитесь к администратору.", "danger")
                return redirect(url_for("main.login"))

            # Проверяем пароль
            hashed_password = user["hashed_password"]
            if not bcrypt.checkpw(password.encode("utf-8"), hashed_password.encode("utf-8")):
                logger.warning(f"Неверный пароль для email {email}.")
                await flash("Неверный email или пароль. Если проблема сохраняется, обратитесь к администратору.", "danger")
                return redirect(url_for("main.login"))

        except ValueError as e:
            logger.error(f"Ошибка при проверке пароля: {e}")
            await flash("Возникла проблема с вашим аккаунтом. Обратитесь к администратору.", "danger")
            return redirect(url_for("main.login"))

        # Успешный вход
        logger.info(f"Пользователь {email} успешно авторизовался.")
        session["user_id"] = str(user["user_id"])  # Используем session для сохранения user_id
        
        # Ручная загрузка ролей
        roles = await get_user_roles(current_app.db_pool, user["user_id"])
        logger.info(f"Роли пользователя: {roles}")

        if "admin" in map(str.lower, roles):  # Проверяем роль "admin"
            logger.info(f"Перенаправление пользователя {email} на /admin/.")
            return redirect(url_for("admin.admin_dashboard"))

        #await flash(f"Добро пожаловать, {user['username']}!", "success")
        return redirect(url_for("main.home"))  # Перенаправляем на главную страницу после авторизации

    logger.info("Отображение страницы авторизации.")
    return await render_template("login.html")


@main.route("/logout")
async def logout():
    """
    Выход из системы.
    """
    logger.info("Пользователь вышел из системы.")
    session.pop("user_id", None)

templates/__base.html
<nav>
    <a href="/">Главная</a>
    <a href="/cart">Корзина</a>
    {% if session.get('user_id') %}
        <a href="/logout">Выход</a>
        <a href="/profile">Профиль</a>
    {% else %}
        <a href="/login">Вход</a>
        <a href="/register">Регистрация</a>
    {% endif %}
</nav>

templates/base.html
<nav>
    <a href="/">Главная</a>
    <a href="/cart">Корзина</a>
    {% if session.get('user_id') %}
        <a href="/logout">Выход</a>
        <a href="/profile">Профиль</a>
    {% else %}
        <a href="/login">Вход</a>
        <a href="/register">Регистрация</a>
    {% endif %}
</nav>

templates/home.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <title>Главная страница - Аренда самокатов</title>
</head>
<body>
    <header>
        <h1>Сервис аренды самокатов</h1>
        <nav>
            <a href="{{ url_for('main.home') }}">Главная</a>
            {% if session.get('user_id') %}
                <a href="/profile">Профиль</a>
                {% if 'Admin' in g.user_roles %}
                    <a href="{{ url_for('admin.admin_dashboard') }}">Админ. панель</a>
                {% endif %}
                <a href="{{ url_for('main.logout') }}">Выход</a>
            {% else %}
                <a href="{{ url_for('main.login') }}">Вход</a>
                <a href="{{ url_for('main.register') }}">Регистрация</a>
            {% endif %}
        </nav>
    </header>
    <main>
        <!-- Форма поиска и фильтрации -->
        <form method="GET" action="{{ url_for('main.home') }}" class="search-form">
            <input type="text" name="q" placeholder="Поиск по модели..." value="{{ request.args.get('q', '') }}" class="search-input">
            <button type="submit" class="search-button">Поиск</button>
            
            <select name="location" class="search-select">
                <option value="" {% if selected_location_id == '' %}selected{% endif %}>Все локации</option>                
                {% for location in locations %}
                    <option value="{{ location.location_id }}" {% if selected_location_id == location.location_id %}selected{% endif %}>
                        {{ location.name }}
                    </option>
                {% endfor %}
            </select>
            
            <label for="min_battery" class="battery-label">Минимальный заряд:</label>
            <input type="number" name="min_battery" min="0" max="100" value="{{ request.args.get('min_battery', 0) }}" class="search-input">
        </form>

        <!-- Список самокатов -->
        <h2>Доступные самокаты</h2>
        <div class="product-list">
            {% if scooters %}
                {% for scooter in scooters %}
                    <div class="product-item">
                        <!-- Ссылка на модель -->
                        <h3>
                            <a href="{{ url_for('main.scooter_page', scooter_id=scooter.scooter_id) }}" class="product-link">
                                {{ scooter.model }}
                            </a>
                        </h3>
                        <p><strong>Заряд батареи:</strong> {{ scooter.battery_level }}%</p>
                        <p><strong>Локация:</strong> {{ scooter.location_name or 'Неизвестно' }}</p>
                        <p><strong>Статус:</strong> 
                            {% if scooter.status == 'available' %}Доступен
                            {% elif scooter.status == 'reserved' %}Забронирован
                            {% elif scooter.status == 'in_use' %}В аренде
                            {% elif scooter.status == 'on_maintenance' %}В обслуживании
                            {% else %}Неизвестный{% endif %}
                        </p>

                        <!-- Кнопки действий -->
                        {% if scooter.status == 'available' %}
                            {% if not user_has_active_reservation %}
                                <form method="POST" action="{{ url_for('main.reserve_scooter_route') }}">
                                    <input type="hidden" name="scooter_id" value="{{ scooter.scooter_id }}">
                                    <input type="hidden" name="action" value="reserve">
                                    <input type="hidden" name="redirect_url" value="{{ request.url }}">
                                    <button type="submit" class="add-to-cart-button">Забронировать</button>
                                </form>
                            {% else %}
                                <p>Вы уже забронировали самокат.</p>
                            {% endif %}
                        {% elif scooter.status == 'reserved' %}
                            {% if scooter.user_reserved %}
                                <form method="GET" action="{{ url_for('main.select_destination', scooter_id=scooter.scooter_id) }}">
                                    <input type="hidden" name="redirect_url" value="{{ request.url }}">
                                    <button type="submit" class="add-to-cart-button">Поехали</button>
                                </form>
                                <form method="POST" action="{{ url_for('main.reserve_scooter_route') }}">
                                    <input type="hidden" name="scooter_id" value="{{ scooter.scooter_id }}">
                                    <input type="hidden" name="redirect_url" value="{{ request.url }}">
                                    <input type="hidden" name="action" value="cancel">
                                    <button type="submit" class="add-to-cart-button">Отменить</button>
                                </form>
                            {% else %}
                                <p>Самокат забронирован другим пользователем.</p>
                            {% endif %}
                        {% elif scooter.status == 'in_use' %}
                            <p>Самокат в аренде.</p>
                        {% elif scooter.status == 'on_maintenance' %}
                            <p>Самокат на обслуживании.</p>
                        {% else %}
                            <p>Неизвестный статус.</p>
                        {% endif %}
                    </div>
                {% endfor %}
            {% else %}
                <p>Самокаты не найдены. Попробуйте изменить параметры поиска.</p>
            {% endif %}
        </div>

        <!-- Пагинация -->
        <div class="pagination">
            <form method="get" action="{{ url_for('main.home') }}" style="display: inline;">
                {% if has_previous %}
                    <input type="hidden" name="page" value="{{ page - 1 }}">
                    <button type="submit">Предыдущая</button>
                {% endif %}
            </form>
            <form method="get" action="{{ url_for('main.home') }}" style="display: inline;">
                {% if has_more %}
                    <input type="hidden" name="page" value="{{ page + 1 }}">
                    <button type="submit">Следующая</button>
                {% endif %}
            </form>
        </div>
    </main>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="../static/styles.css">
</head>
<body>
    <h1>Login</h1>

    <!-- Блок для отображения сообщений -->
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="messages">
                {% for category, message in messages %}
                    <p class="message {{ category }}">{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}

    <!-- Форма для входа -->
    <form action="/login" method="post" class="auth-form">
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
        <button type="submit">Login</button>
        <a href="/register" class="secondary-link">Don't have an account? Register here</a>
        <a href="/" class="secondary-link">Continue as Guest</a>
    </form>
</body>
</html>

templates/profile.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Профиль</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <style>
        /* Стили для точек и выравнивания списка */
        .recent-rentals ul {
            list-style-type: disc; /* Восстанавливаем маркеры списка */
            padding-left: 20px; /* Отступ для маркеров */
        }
    
        .recent-rentals li {
            margin-bottom: 10px; /* Расстояние между элементами списка */
        }
    
        .recent-rentals p {
            margin: 5px 0; /* Выравнивание отступов параграфов */
        }
        button {
            margin-top: 20px;
            background: none; /* Убираем фон */
            border: none; /* Убираем границу */
            color: #007BFF; /* Цвет, как у ссылки */
            text-decoration: underline; /* Подчеркивание */
            font-size: 16px;
            cursor: pointer; /* Курсор в виде указателя */
        }
        button:hover {
            color: #0056b3; /* Цвет при наведении */
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <header>
        <h1>Ваш профиль</h1>
        <nav>
            <a href="{{ url_for('main.home') }}">Главная</a>
            {% if session.get('user_id') %}
                <a href="{{ url_for('main.profile') }}">Профиль</a>
                {% if 'Admin' in g.user_roles %}
                    <a href="{{ url_for('admin.admin_dashboard') }}">Админ. панель</a>
                {% endif %}
                <a href="{{ url_for('main.logout') }}">Выход</a>
            {% else %}
                <a href="{{ url_for('main.login') }}">Вход</a>
                <a href="{{ url_for('main.register') }}">Регистрация</a>
            {% endif %}
        </nav>
    </header>
    <main>
        <div class="profile-info">
            <p><strong>Email:</strong> {{ email or 'N/A' }}</p>
            <p><strong>Username:</strong> {{ username or 'N/A' }}</p><br>
        </div>

        <section class="recent-rentals">
            <h3>Последние поездки</h3>

            <!-- Кнопки пагинации -->
            <div class="pagination" style="margin-top: 10px">
                <form method="get" action="{{ url_for('main.profile') }}" style="display: inline;">
                    {% if page > 1 %}
                        <input type="hidden" name="page" value="{{ page - 1 }}">
                        <button type="submit" style="background-color: #007bff; color: white; border: none; padding: 5px 10px; border-radius: 4px; cursor: pointer;">
                            Предыдущая
                        </button>
                    {% endif %}
                </form>
                <form method="get" action="{{ url_for('main.profile') }}" style="display: inline;">
                    {% if has_more %}
                        <input type="hidden" name="page" value="{{ page + 1 }}">
                        <button type="submit" style="background-color: #007bff; color: white; border: none; padding: 5px 10px; border-radius: 4px; cursor: pointer;">
                            Следующая
                        </button>
                    {% endif %}
                </form>
            </div>

            {% if last_rentals %}
                <ul>
                    {% for rental in last_rentals %}
                        <li>
                            <p>
                                <strong>Дата завершения поездки:</strong> 
                                {{ rental.end_time.strftime('%Y-%m-%d %H:%M') if rental.end_time else 'N/A' }}
                            </p>
                            <p><strong>Стоимость:</strong> 
                                {{ rental.total_price if rental.total_price is not none else 'N/A' }} ₽
                            </p>
                            <p><strong>Локации:</strong></p>
                            <ul>
                                <li>Начальная: {{ rental.start_location_name or 'N/A' }}</li>
                                <li>Конечная: {{ rental.end_location_name or 'N/A' }}</li>
                            </ul>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>У вас пока нет поездок.</p>
            {% endif %}

        </section>
    </main>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    <link rel="stylesheet" href="../static/styles.css">
</head>
<body>
    <h1>Register</h1>
    <form action="/register" method="post" class="auth-form">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
        <button type="submit">Register</button>
        <a href="/login" class="secondary-link">Already have an account? Login here</a>
        <a href="/" class="secondary-link">Continue as Guest</a>
    </form>
</body>
</html>

templates/scooter_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ scooters.model }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <header>
        <h1>{{ scooters.model }}</h1>
        <nav>
            <a href="{{ url_for('main.home') }}">Главная</a>
            {% if session.get('user_id') %}
                <a href="/profile">Профиль</a>
                {% if 'Admin' in g.user_roles %}
                    <a href="{{ url_for('admin.admin_dashboard') }}">Админ. панель</a>
                {% endif %}
                <a href="{{ url_for('main.logout') }}">Выход</a>
            {% else %}
                <a href="{{ url_for('main.login') }}">Вход</a>
                <a href="{{ url_for('main.register') }}">Регистрация</a>
            {% endif %}
        </nav>
    </header>
    <main>
        <!-- Блок для отображения сообщений -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="messages">
                    {% for category, message in messages %}
                        <p class="message {{ category }}">{{ message }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}

        <p><strong>Локация:</strong> {{ scooters.location_name or 'N/A' }}</p>
        <p><strong>Статус:</strong> {{ scooters.status }}</p>
        <p><strong>Текущий заряд:</strong> {{ scooters.battery_level }}%</p>
        <p><strong>Энергопотребление:</strong> {{ scooters.battery_consumption }}% /км</p>
        <p><strong>Ограничение скорости:</strong> {{ scooters.speed_limit }} км/ч</p>
        <p><strong>Дата последнего обслуживания:</strong> {{ scooters.last_maintenance_date.strftime('%Y-%m-%d %H:%M') if scooters.last_maintenance_date else 'N/A' }}</p>

        <!-- Кнопки действий в зависимости от статуса -->
        {% if scooters.status == 'available' %}
            <form method="POST" action="{{ url_for('main.reserve_scooter_route') }}">
                <input type="hidden" name="scooter_id" value="{{ scooters.scooter_id }}">
                <input type="hidden" name="action" value="reserve">
                <input type="hidden" name="redirect_url" value="{{ request.url }}"> <!-- Добавлено поле -->
                <button type="submit" class="action-button">Забронировать</button>
            </form>
        
        {% elif scooters.status == 'reserved' and session.get('user_id') and scooters.user_reserved %}
            <form method="GET" action="{{ url_for('main.select_destination', scooter_id=scooters.scooter_id) }}">
                <input type="hidden" name="redirect_url" value="{{ request.url }}"> <!-- Добавлено поле -->
                <button type="submit" class="action-button">Поехали</button>
            </form>
            <form method="POST" action="{{ url_for('main.reserve_scooter_route') }}">
                <input type="hidden" name="scooter_id" value="{{ scooters.scooter_id }}">
                <input type="hidden" name="action" value="cancel">
                <input type="hidden" name="redirect_url" value="{{ request.url }}"> <!-- Добавлено поле -->
                <button type="submit" class="action-button">Отменить</button>
            </form>
        {% else %}
            <p>Этот самокат недоступен для бронирования или использования в данный момент.</p>
        {% endif %}

        <h3>Отзывы</h3>
        {% if reviews %}
            <ul>
                {% for review in reviews %}
                    <li>
                        <p><strong>{{ review.username }}</strong> ({{ review.review_date.strftime('%Y-%m-%d %H:%M') or 'N/A' }})</p>
                        <p>Оценка: {{ review.rating }} / 5</p>
                        <p>{{ review.review_text }}</p>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Пока нет отзывов на этот самокат.</p>
        {% endif %}

        {% if session.get('user_id') %}
        <h3>Оставить отзыв</h3>
        {% if not last_rental %}
            <p>Вы не можете оставить отзыв, так как у вас нет завершенных поездок на этом самокате.</p>
        {% elif last_rental and not last_rental.has_review %}
            <form method="POST">
                <input type="hidden" name="rental_id" value="{{ last_rental.id }}">
                <p>
                    <label for="rating">Оценка:</label>
                    <select name="rating" id="rating">
                        <option value="5">5</option>
                        <option value="4">4</option>
                        <option value="3">3</option>
                        <option value="2">2</option>
                        <option value="1">1</option>
                    </select>
                </p>
                <p>
                    <label for="review_text">Комментарий:</label><br>
                    <textarea name="review_text" id="review_text" rows="5" cols="50" required></textarea>
                </p>
                <button type="submit">Отправить отзыв</button>
            </form>
        {% else %}
            <p>Вы не можете оставить отзыв, так как вы уже оставили отзыв для этой поездки.</p>
        {% endif %}
        {% else %}
            <p><a href="{{ url_for('main.login') }}">Войдите в систему</a>, чтобы оставить отзыв.</p>
        {% endif %}
    </main>
</body>
</html>